theme: jekyll-theme-cayman
title: SmmServer
description: Open source private server for Super Mario Maker (Wii U), integrated with SMMDB and Cemu
download: https://mega.nz/file/qR9xgTyB#ZK7L-PsD4TEbDkSKhwenXISMhXeeaiyRIjJiQ36rIBs
