theme: jekyll-theme-cayman
title: SmmServer
description: Open source private server for Super Mario Maker (Wii U), integrated with SMMDB and Cemu
download: https://mega.nz/file/HFE1yRAa#Cft6DYmSUbyr3JUIIkyBWCULtQr1vmk8LUKf-6pu3X4
